---
title: "Case Study 11"
author: Kaiser Mahmood
date: December 17, 2020
output: github_document
---

```{r library}
library(tidyverse)
library(spData)
library(sf)
library(tidycensus)

## New Packages
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers() # check registered cores

```

```{r preparing data, echo = F, eval = T, message= F}
#census_api_key("Removed", install=TRUE)
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")

options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                  state = "NY", county = "Erie County", geometry = TRUE,
                  summary_var = "P001001", cache_table=T) 
```

```{r echo = F, eval = T, message= F}
crop_data <- c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
erie_crop <- st_crop(erie, crop_data)
erie_crop$variable = as.factor(erie_crop$variable)
```

```{r map, echo = F, eval = T, message= F}
buffalo_dots <- foreach(i = 1:4, .combine = rbind, .packages = c("tidyverse", "sf")) %dopar% {
    race <- levels(erie_crop$variable)[i]
    erie_crop %>%
    filter(variable == race)%>% 
    st_sample(size = .$value)%>%
    st_as_sf()%>%
    mutate(variable = race)
}
mapview(buffalo_dots, zcol = "variable", cex = 0.8, alpha = 0) #tried different cex and alpha. With the current two values the map looked good for me.

#looked at brendan's code for the foreach loop
```